Dpdk-ovs: Fix autoconf related issues
As brought up by Shu Shen in a different thread, this is necessary only compiling against theDPDK in dpdk.org.
If DPDK-OVS does not support that DPDK we might want to drop this patch.

-----Original Message-----
From: Gasparakis, Joseph
Sent: Thursday, December 26, 2013 12:35 PM
To: dpdk-ovs at ml01.01.org
Cc: Gasparakis, Joseph
Subject: [PATCH] Dpdk-ovs: Fix autoconf related issues

This patch allows autoconf to detect possible dependences with libdl as reported by TSADOK, Shlomi (Shlomi):

/root/dpdk/dpdk-1.4.1r2//x86_64-default-linuxapp-gcc/lib/librte_eal.a(eal.o): In function `rte_eal_init':
eal.c:(.text+0xf29): undefined reference to `dlopen'
eal.c:(.text+0xf63): undefined reference to `dlopen'
eal.c:(.text+0xf86): undefined reference to `dlerror'
collect2: error: ld returned 1 exit status
make[2]: *** [utilities/ovs-dpctl] Error 1
make[2]: Leaving directory `/root/ovs_dpdk/openvswitch'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/ovs_dpdk/openvswitch'
make: *** [all] Error 2

Also boot.sh seemed not to have the right execution permissions.

Change-Id: Ia631381177a2eef3c027a6d84d873e9271fd5fe9
Reported-by: TSADOK, Shlomi (Shlomi) <shlomi.tsadok at alcatel-lucent.com>
Signed-off-by: Joseph Gasparakis <joseph.gasparakis at intel.com>
Acked-by: Mark D. Gray <mark.d.gray@intel.com>